/*
 * generated by Xtext 2.25.0
 */
package hu.bme.aut.statechartdsl.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class StatechartDSLWebModule extends AbstractStatechartDSLWebModule {
}
