/*
 * generated by Xtext 2.25.0
 */
package hu.bme.aut.statechartdsl.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import hu.bme.aut.statechartdsl.StatechartDSLRuntimeModule;
import hu.bme.aut.statechartdsl.StatechartDSLStandaloneSetup;
import hu.bme.aut.statechartdsl.ide.StatechartDSLIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class StatechartDSLWebSetup extends StatechartDSLStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new StatechartDSLRuntimeModule(), new StatechartDSLIdeModule(), new StatechartDSLWebModule()));
	}
	
}
