package SolidMaker.sandbox;

/*Generated by MPS */

import javafx.application.Application;
import javafx.stage.Stage;
import javafx.scene.Group;
import javafx.scene.shape.Sphere;
import javafx.scene.Scene;
import javafx.scene.PerspectiveCamera;

public class MyScene extends Application {
  public static void main(String[] args) {
    Application.launch(args);
  }

  @Override
  public void start(Stage stage) throws Exception {
    Group root = new Group();
    
    {
      Sphere sphere = new Sphere();
      sphere.setTranslateX(50);
      sphere.setTranslateY(50);
      sphere.setTranslateZ(0);
      sphere.setRadius(10);
      root.getChildren().add(sphere);
    };
    
    {
      Sphere sphere = new Sphere();
      sphere.setTranslateX(200);
      sphere.setTranslateY(200);
      sphere.setTranslateZ(0);
      sphere.setRadius(40);
      root.getChildren().add(sphere);
    };
    
    {
      Sphere sphere = new Sphere();
      sphere.setTranslateX(350);
      sphere.setTranslateY(350);
      sphere.setTranslateZ(0);
      sphere.setRadius(90);
      root.getChildren().add(sphere);
    };
    Scene scene = new Scene(root, 1000, 500);
    PerspectiveCamera cam = new PerspectiveCamera(false);
    cam.setTranslateX(0);
    cam.setTranslateY(0);
    cam.setTranslateZ(0);
    scene.setCamera(cam);
    stage.setTitle("MyScene");
    stage.setScene(scene);
    stage.show();
  }
}
