/*
 * generated by Xtext 2.25.0
 */
package hu.bme.aut.statechartdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class StatechartDSLUiModule extends AbstractStatechartDSLUiModule {

	public StatechartDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
