/*
 * generated by Xtext 2.25.0
 */
package hu.bme.aut.statechartdsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class StatechartDSLStandaloneSetup extends StatechartDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new StatechartDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
