/*
 * generated by Xtext 2.25.0
 */
package hu.bme.aut.statechartdsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import hu.bme.aut.statechartdsl.StatechartDSLRuntimeModule;
import hu.bme.aut.statechartdsl.StatechartDSLStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class StatechartDSLIdeSetup extends StatechartDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new StatechartDSLRuntimeModule(), new StatechartDSLIdeModule()));
	}
	
}
