/*
 * generated by Xtext 2.25.0
 */
package hu.bme.aut.statechartdsl.ide;


/**
 * Use this class to register ide components.
 */
public class StatechartDSLIdeModule extends AbstractStatechartDSLIdeModule {
}
