//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.EchoService")]
    public interface EchoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EchoService/Echo", ReplyAction="http://tempuri.org/EchoService/EchoResponse")]
        string Echo(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EchoService/Echo", ReplyAction="http://tempuri.org/EchoService/EchoResponse")]
        System.Threading.Tasks.Task<string> EchoAsync(string text);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EchoServiceChannel : Client.ServiceReference1.EchoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EchoServiceClient : System.ServiceModel.ClientBase<Client.ServiceReference1.EchoService>, Client.ServiceReference1.EchoService {
        
        public EchoServiceClient() {
        }
        
        public EchoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EchoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EchoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EchoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Echo(string text) {
            return base.Channel.Echo(text);
        }
        
        public System.Threading.Tasks.Task<string> EchoAsync(string text) {
            return base.Channel.EchoAsync(text);
        }
    }
}
